# Generated by Django 4.2.7 on 2023-12-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0002_queries_userdetails_delete_traineedet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
