# Generated by Django 4.2.7 on 2023-12-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0004_rename_userdetails_trainee_trainer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainee',
            new_name='userdetails',
        ),
        migrations.DeleteModel(
            name='queries',
        ),
        migrations.DeleteModel(
            name='trainer',
        ),
    ]
