# Generated by Django 4.2.7 on 2023-12-23 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0005_rename_trainee_userdetails_delete_queries_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userdetails',
            new_name='alldetails',
        ),
        migrations.CreateModel(
            name='trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.alldetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trainees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.alldetails')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
