# Generated by Django 4.2.7 on 2023-12-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0006_rename_userdetails_alldetails_trainers_trainees'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainerAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.trainers')),
            ],
        ),
    ]
