# Generated by Django 4.2.7 on 2023-12-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_trainerattendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendence',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
