# Generated by Django 4.2.7 on 2023-12-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0009_assigntrainee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainees',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.trainers'),
        ),
        migrations.DeleteModel(
            name='assignTrainee',
        ),
    ]
