# Generated by Django 4.2.7 on 2023-12-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0015_tasks_docs_tasks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
