# Generated by Django 4.2.7 on 2023-12-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0016_tasks_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='docs',
        ),
        migrations.CreateModel(
            name='submittedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(null=True)),
                ('docs', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('delay', models.CharField(max_length=20, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.tasks')),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.trainees')),
            ],
        ),
    ]
