# Generated by Django 4.2.7 on 2023-12-26 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0017_remove_tasks_desc_remove_tasks_docs_submittedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='Unread', max_length=20, null=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingapp.trainers')),
            ],
        ),
    ]
