# Generated by Django 4.2.7 on 2023-12-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0020_traineenotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
    ]
