# Generated by Django 4.2.7 on 2023-12-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0022_remove_tasks_status_submittedtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedtask',
            name='status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
    ]
